### ISSUE TITLE
"Programtext zeigen" in the script menu is broken

### ISSUE THREAD

**Issue by JensLincke** [timfel/etoys-spur#6] opened 2016-08-19 11:54 UTC

**Comment by timfel** [comment] 2016-08-21 16:35
That's when you tried it in a kedama turtle script, right?

**Comment by JensLincke** [comment] 2016-08-21 22:16
Yes, it is broken only in kedama

**Comment by timfel** [comment] 2016-08-22 07:40
Ok, I tried this and it actually is only broken when you use the script from the KedamaTurtle itself. If you put the kedama turtle tiles in a script on the kedama world, then it appears to work correctly. The problem is a decompiler bug that I'm looking at now.

**Comment by timfel** [comment] 2016-08-31 18:56
Should be fixed

**Closed as completed by timfel** 2016-08-31 18:56 UTC
